# Copyright 2018 Google LLC.
# SPDX-License-Identifier: Apache-2.0

package(default_visibility = ["//visibility:public"])

# This rule is license under Apache 2
licenses(["notice"])  # Apache 2

alias(
    name = "cup_bin",
    actual = "//third_party/cup:cup_bin",
)
