java_test(
    name = "CaselessScannerTest",
    srcs = ["CaselessScannerTest.java"],
    deps = [
        "//java/jflex/examples/jlex:caseless_jflex_scanner",
        "//java/jflex/examples/jlex:token",
        "//third_party/com/google/guava",
        "//third_party/com/google/truth",
    ],
)
