# Copyright 2018 Google LLC.
# SPDX-License-Identifier: Apache-2.0

container:
  image: l.gcr.io/google/bazel:3.5.0
  memory: 4G

task:
  build_script:
  - bazel --bazelrc=.cirrus.bazelrc build --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST //...
  test_script:
  - bazel --bazelrc=.cirrus.bazelrc test --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST //...
