# Copyright 2018 Google LLC.
# SPDX-License-Identifier: Apache-2.0

package(default_visibility = ["//visibility:public"])

java_library(
    name = "exception",
    srcs = ["CalculatorParserException.java"],
)
