# Copyright 2018 Google LLC.
# SPDX-License-Identifier: Apache-2.0

java_test(
    name = "HelloWorldTest",
    srcs = ["HelloWorldTest.java"],
    data = ["testdata.txt"],
    deps = [
        "//java/jflex/examples/helloworld",
        "//third_party/com/google/guava",
    ],
)
