java_test(
    name = "NestedGrammarTest",
    srcs = ["NestedGrammarTest.java"],
    deps = [
        "//java/jflex/examples/nested_grammar",
        "//third_party/com/google/guava",
        "//third_party/com/google/truth",
    ],
)
