java_test(
    name = "CalculatorLexerTest",
    srcs = ["CalculatorLexerTest.java"],
    deps = [
        "//java/jflex/examples/cup_calculator",
        "//third_party/cup",
        "//third_party/com/google/truth",
    ],
)

java_test(
    name = "CalculatorParserTest",
    srcs = ["CalculatorParserTest.java"],
    deps = [
        "//java/jflex/examples/cup_calculator",
        "//third_party/cup",
        "//third_party/com/google/truth",
    ],
)
