java_test(
    name = "CalculatorLexerTest",
    srcs = ["CalculatorLexerTest.java"],
    deps = [
        "//java/jflex/examples/calculator",
        "//third_party/cup",
        "//third_party/com/google/truth",
    ],
)
